language: ruby
cache: bundler
bundler_args: --without development
rvm:
- 2.5
- 2.4
- 2.3
- rbx-3
env:
  global:
    - AEROSPIKE_HOSTS=127.0.0.1:3000,127.0.0.1:3100
    - CODECOV_ENABLED=true
sudo: false
os:
- linux
dist: trusty
matrix:
  allow_failures:
  - rvm: rbx-3
  fast_finish: true
before_script:
- .travis/start_cluster.sh 2
install:
- bundle install
script:
- bundle exec rspec
after_script:
- tail -n +1 aerospike-server/instance?/var/log/aerospike.log
notifications:
  hipchat:
    rooms:
      secure: H5qTvLxIBBinW4eE6D/x1+BBLUeOb+7dq3wkgSR8IUTGoBZ2bbVWwqNbKUJ1ueuKs4g9RvV7sDkG03dSze/lZJcE+bOMfIGkmBRl0InnTZdGvAs9QD2DCs6d+iNWBM9OvIPvjyTBJ2ryhmYcB2NFr2Nubl0xgdzFJA2BOAvHLK0=
  slack:
    secure: eTiZiYHWKgwzvR0VksJgaR3fOK4+HTT4vN+3N8/n4RUXAnzEEurvpAbwFwF0e47a5Pt1ro731Je/lgO6BXWsa8Cy/ZtuF/33VhKSaWsMopYfOcoGpGyc8GH3pz/7fnT9kz/f6ZSGpp+BV+hK8dYu3x5kKWCQ7VTq33CNEYLmcow=
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
