name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        os:
          - ubuntu
          # - macos

        ruby:
          - "2.6"
          - "3.3"

        experimental: [false]
        env: [""]

    steps:
      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run tests
        timeout-minutes: 30
        env:
          AEROSPIKE_HOSTS: "127.0.0.1:3000"
          CODECOV_ENABLED: "false"
        run: ${{matrix.env}} bundle exec rspec
