name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        os:
          - ubuntu
          # - macos

        ruby:
          - "2.6"
          - "3.3"

        experimental: [false]
        env: [""]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@2065a9209cfd5ef88a3e07f3e7929e321d1e0067 # v1.1.0
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run tests
        timeout-minutes: 30
        env:
          AEROSPIKE_HOSTS: "127.0.0.1:3000"
          CODECOV_ENABLED: "false"
        run: ${{matrix.env}} bundle exec rspec
