name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest

        ruby:
          #- "2.6"
          #- "2.7"
          #- "3.0"
          #- "3.1"
          #- "3.2"
          - "3.3"

        experimental: [false]
        env: [""]

        include:
          - os: ubuntu
            ruby: head
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
      - name: Run tests
        timeout-minutes: 30
        env:
          AEROSPIKE_HOSTS: "127.0.0.1:3000"
        run: ${{matrix.env}} bundle exec rspec
